name: Docker Deploy

on:
  push:
    branches:
      - main

jobs:
  docker:
    name: Build Docker Image
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: |
            ghcr.io/emmaboecker/emmalink:latest
            ghcr.io/emmaboecker/emmalink:"$GITHUB_SHA"
          platforms: linux/amd64
